# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9db5eb8c154e861aee43878d99ef9b4308302573551c343c053fd76d7b1853c8bfa0d5027ceb68b7f6ded63012e1f6255a6b170463fed32eb96be6710ae880d

test:
  secret_key_base: 1128673b9b256e64214688cb002fb8cc0f630c79c47327575044765928ef7ec260a529ed10bb18e345a5ede0ac58f4fb91eb6bad6e5be2814b899ec3f407662f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
